### ISSUE TITLE
Reduce number of transitive dependencies

### ISSUE THREAD

**Issue by MicahZoltu** [GervinFung/ts-add-js-extension#12]
![image](https://user-images.githubusercontent.com/886059/188788248-7826e108-7305-4173-bef8-d71bcb2e4fad.png)

This script *feels* like something that could be written with no dependencies (except NodeJS built-in libraries), but it currently has 55 dependencies.  Can any of these dependencies be removed without too much effort, or are they absolutely critical in making this work?

**Comment by GervinFung** [comment]
Hey thanks for the feedback, I had removed `parse-dont-validate` as I can parse some of the command line argument received from `yargs` myself. However I think I will have to keep `yargs` to parse other command line option (makes my life easier) and `@typescript-eslint/typescript-estree` for finding import/export statement, I think that is more reliable than using regex itself

As for `console-table-printer`, I think it's optional to have that package, as it only shows what has been changed. Arguably I can also do that with `console.table` or write a more flexible table printer function. The package makes my life easier although its optional

Do you have other suggestions?

**Comment by MicahZoltu** [comment]
I haven't looked into the project deeply enough to identify what can/can't be pulled out.  My personal preference would be to have a tool that doesn't handle edge cases as well and/or has fewer CLI options but is dependency free over one with a large number of dependencies but has more options and covers all edge cases.  I may not be your target demographic though.  😆

**Comment by MicahZoltu** [comment]
Another option would be to look for alternatives that solve similar problems but with fewer *transitive* dependencies.  For example, I suspect there is probably a CLI argument parser out there that has no transitive dependencies, thus turning 16 dependencies into 1 dependency.

**Comment by GervinFung** [comment]
Do u mind telling me what tools do u used to display the graph of dependencies

**Comment by MicahZoltu** [comment]
http://npm.anvaka.com/#/

**Comment by GervinFung** [comment]
I kept this in mind and I've written a CLI parser, removing `yargs`, I still use `@typescript-eslint/typescript-estree` because of its simple AST, Microsoft Typescript compiler is one of the option but it seems complicated than the one I am using now. Are you aware of an alternative that has less transitive dependencies?

![image](https://github.com/GervinFung/ts-add-js-extension/assets/53143214/11e343ca-dfcd-4636-8d05-01a5615df055)

**Comment by MicahZoltu** [comment]
Very happy to see the removal of yangs, that is a substantial step in the right direction IMO!  😁

From a security standpoint, fewer transitive dependencies means fewer potential supply chain attack vectors.  An attacker only needs to compromise one transitive dependency in order to execute arbitrary code on any developer/build machine that installs the library (assuming the users don't proactively disable install-scripts).  If you have a single transitive dependency (e.g., `typescript`), then there is only one place to try to attack and in this case I suspect Microsoft's security around their build/deploy system is more robust than say, `yallist`.

As far as install time goes, size definitely matters but a single large file can download/install quite quickly while many transitive dependencies can slow down install times significantly due to sequential processing that needs to happen (you need to first get the `package.json` for a dependency, and then fetch its dependencies' `package.json`s, etc.).

**Comment by GervinFung** [comment]
After some thoughts, and trying out different parser, I decided to go with `tsc`, I only had to install 1 package for parsing and packaging. Besides, most parser contains external package(s), or has no type definition (yikes)

**Comment by MicahZoltu** [comment]
Down to 1 dependency from 55, great achievement!
