### ISSUE TITLE
Feature request: also add .js extension for .d.ts file

### ISSUE THREAD

**Issue by xiaoxiangmoe** [GervinFung/ts-add-js-extension#28]
change 
```ts
// main.d.ts
import { appRouter } from './routers';
```

to 

```ts
// main.d.ts
import { appRouter } from './routers/index.js';
```

**Comment by xiaoxiangmoe** [comment]
@GervinFung Hi， any idea about this?

**Comment by GervinFung** [comment]
Hi @xiaoxiangmoe, it will be easy to add this, but I am a bit confused, is this necessary? Why do u need to change the path and what can u do after changing the path?

**Comment by xiaoxiangmoe** [comment]
@GervinFung this is necessary.
If we want to release an npm library with package.json `"type": "module"`. And library user use it with tsconfig `"moduleResolution": "nodenext"`. tsc will not recognize `'./routers'`, but it will recognize `'./routers/index.js'`.

**Comment by GervinFung** [comment]
Can u give me a mini-project for me to try?

**Comment by xiaoxiangmoe** [comment]
https://github.com/xiaoxiangmoe/ts-add-js-extension-library-type-error

Here is a example. 

Also, please run it in mac or linux, beacause ts-add-js-extension is not support windows now.

**Comment by GervinFung** [comment]
Hey @xiaoxiangmoe, I pushed latest update to [here](https://github.com/GervinFung/ts-add-js-extension/tree/add-extension-to-dts), would u like to try it out before I publish it? Thanks!

**Comment by xiaoxiangmoe** [comment]
```text
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0

YOUR TYPESCRIPT VERSION: 5.0.2

Please only submit bug reports when using the officially supported version.

=============
```

Maybe we should update @typescript-eslint/typescript-estree version

**Comment by xiaoxiangmoe** [comment]
Also, this new version seems not working for me. I'll create a demo to show it latter.

**Comment by xiaoxiangmoe** [comment]
I update @typescript-eslint/typescript-estree version and I also find another bug here.

https://github.com/xiaoxiangmoe/ts-add-js-extension-library-type-error

see demo nodenext-type-error

**Comment by xiaoxiangmoe** [comment]
Hi, I create a PR to fix it.

**Comment by xiaoxiangmoe** [comment]
@GervinFung I try it out. It works well in my mac and linux. Thanks

**Comment by GervinFung** [comment]
> @GervinFung I try it out. It works well in my mac and linux. Thanks

U pointed out the problem, I only merge and publish it. Also, I learnt something new too, so, thank you
