### ISSUE TITLE
Bug: windows support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [GervinFung/ts-add-js-extension#29]
This library is not working on windows

**Comment by GervinFung** [comment]
Can you show me how it's not working?

**Comment by xiaoxiangmoe** [comment]
I don't have windows currently. But I remember that 

https://github.com/GervinFung/ts-add-js-extension/blob/d5796197bfa692ab45240865f64028e5cefb836e/src/traverse-and-update.ts#L41-L58

The filePath here in windows is `'lib\\foo\\bar'` but in macOS is  `'lib/foo/bar'` .

**Comment by xiaoxiangmoe** [comment]
Let me provide you some e2e test

**Comment by GervinFung** [comment]
@xiaoxiangmoe is the test ready?

**Comment by xiaoxiangmoe** [comment]
I found your test case is good enough to find windows compatibility issues. 
By the way, I fixed the bug, see pr for details.

**Comment by GervinFung** [comment]
> I don't have windows currently. But I remember that
> 
> https://github.com/GervinFung/ts-add-js-extension/blob/d5796197bfa692ab45240865f64028e5cefb836e/src/traverse-and-update.ts#L41-L58
> 
> The filePath here in windows is `'lib\\foo\\bar'` but in macOS is `'lib/foo/bar'` .

Ok, understood, recently just got Windows work laptop, can find the issue

**Comment by xiaoxiangmoe** [comment]
@GervinFung  See my fix https://github.com/GervinFung/ts-add-js-extension/pull/45
