### ISSUE TITLE
Missing documented --extension CLI option?

### ISSUE THREAD

**Issue by devidw** [GervinFung/ts-add-js-extension#31]
In the project's README, an `--extension` option is mentioned: "--extension=mjs" https://github.com/GervinFung/ts-add-js-extension/blob/a3f4ffca2d8367b0e53d8b57129df0bdb7cf083c/README.md

However, the CLI itself (version: 1.3.3) doesn't seem to ship this feature?

```plain
ts-add-js-extension.js add

Use to add .js extension for the relative import/export statement in the
JavaScript code if there is lack of .js extension in the import/export
statement.

Options:
  --version      Show version number                                   [boolean]
  --help         Show help                                             [boolean]
  --dir          The folder that need to add .js extension   [string] [required]
  --include      The folder of files that is imported or included in `dir`
                 folder, exclusing the `dir` specified                   [array]
  --showchanges  Show changes made to import/export declaration in table format
                                                       [boolean] [default: true]

Unknown argument: extension
```

Feel free to correct me if I am missing something here.

**Comment by GervinFung** [comment]
Previously `extension` was needed so I update the README and its code and pushed, but it was not published at that time because, I realized `mjs` can import into `js` and vice versa, then I write code that can automatically append `js` or `mjs` without using `extension`

So sorry for the confusing docs

**Comment by devidw** [comment]
Alright I see, thanks for your clarification 🙌

**Comment by GervinFung** [comment]
Hey, I forgot to ask, are u using `.mjs` file extension for this issue? Or just wanna report a possible bug in CLI

**Comment by devidw** [comment]
The latter one :)

> Or just wanna report a possible bug in CLI
