### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jimmywarting** [GervinFung/ts-add-js-extension#34]
> Initially I wrote it only for myself because I don't like to have .js in my TypeScript import/export statement if I were to compile my TypeScript project to ESNext Module. The main reason being, I should not be importing a JavaScript file that do not exists, there's no JavaScript file in the source code folder being referenced at all and importing/exporting a file that don't exists makes no sense. In conclusion, a source code should not be referring to it's own build artifacts/output

I so much agree with this statement. if it dose not exist then it should not try to import it. 
also you might have a `math.js` and a `math.ts` that could do completely different thing.
so i think it's good even for TypeScript to be explicit. 

So i actually think this example
```js
import { add } from './math';
export { add, sub, mul, div } from './math';

import div from './math/div';
export * as div from './math/div';

console.log(add(2, 1));
```
should rather be:
```js
import { add } from './math.ts';
export { add, sub, mul, div } from './math.ts';

import div from './math/div.ts';
export * as div from './math/div.ts';

console.log(add(2, 1));
```
and when you are compiling then it should rename eg: `math.ts` to `math.js`
Remote http resolver don't have access to the file system so it can't guess what you meant to import. 

is `./math` a folder or a file. is it `js` or `ts` or maybe it's a `math.json`? who knows. either way the problem is that http loader can't be able to find either `math.ts` or `math.js` if you have a http resolver that transpile typescript on the fly. like Deno.

**Comment by GervinFung** [comment]
Hey, thanks for pointing out, you are right, I felt the example is a bit off actually, I'll change the example
