### ISSUE TITLE
No extension added for sub module ESM syntax 

### ISSUE THREAD

**Issue by staplespeter** [GervinFung/ts-add-js-extension#39]
Hi, thanks again for the work.  One case I encountered where it did not add a .js was when using the [submodule syntax on the date-fns package](https://date-fns.org/v2.30.0/docs/Getting-Started#submodules).  I'm fairly new to Typescript so I'm not sure if this is a valid issue or not.  The date-fns package does mention the submodule syntax [in regards to bundlers](https://date-fns.org/v2.30.0/docs/ECMAScript-Modules), so I'm not sure if it should only be picked up by them.  VSCode and Typescript are happy to parse and transpile the syntax however.

my example:
`import add from 'date-fns/add';`

**Comment by GervinFung** [comment]
Hi, `data-fnd` is a package, a package do not need any JavaScript file extension at the end of import/export statements to work, however, relative import/export need it

So

`import add from 'data-fns/add` is not a relative import, so it will work well
`import add from '../add'` is relative import, as it's from your project, so it will be transformed to `import add from '../add.js'` or `import add from '../add.mjs'`, depending on what file you imported

**Comment by staplespeter** [comment]
Hi, thank you for the reply.  In principle. yes, I understand.  However, I do receive the following error in the above case:

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/mnt/Data/Repos/Demo-Project/node_modules/date-fns/add' is not supported resolving ES modules imported from /mnt/Data/Repos/Demo-Project/build/Model/UserSession.js
Did you mean to import date-fns/add/index.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:400:17)
    at moduleResolve (node:internal/modules/esm/resolve:965:10)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at nextResolve (node:internal/modules/esm/loader:173:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///mnt/Data/Repos/Demo-Project/node_modules/date-fns/add'
}
```
So this made me think that perhaps there was a case not covered.  date-fns/add/index.js does exist, and the bare import specifier of a default export seems a valid syntax for ESM, so wasn't sure why Node threw the error.

**Comment by GervinFung** [comment]
> Hi, thank you for the reply. In principle. yes, I understand. However, I do receive the following error in the above case:
> 
> ```
> Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/mnt/Data/Repos/Demo-Project/node_modules/date-fns/add' is not supported resolving ES modules imported from /mnt/Data/Repos/Demo-Project/build/Model/UserSession.js
> Did you mean to import date-fns/add/index.js?
>     at new NodeError (node:internal/errors:387:5)
>     at finalizeResolution (node:internal/modules/esm/resolve:400:17)
>     at moduleResolve (node:internal/modules/esm/resolve:965:10)
>     at defaultResolve (node:internal/modules/esm/resolve:1173:11)
>     at nextResolve (node:internal/modules/esm/loader:173:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
>     at link (node:internal/modules/esm/module_job:75:36) {
>   code: 'ERR_UNSUPPORTED_DIR_IMPORT',
>   url: 'file:///mnt/Data/Repos/Demo-Project/node_modules/date-fns/add'
> }
> ```
> 
> So this made me think that perhaps there was a case not covered. date-fns/add/index.js does exist, and the bare import specifier of a default export seems a valid syntax for ESM, so wasn't sure why Node threw the error.
> 
> The transpiled UserSession.js file also contains `import add from 'date-fns/add';`.
> 
> Using `import { add } from 'date-fns';` works and is always output unaltered. Apologies if this issue is unrelated to your package.

It should be their package problem, but do u mind sharing with me an example of the project u r working on, at least the minimum setup that leads to this issue

**Comment by staplespeter** [comment]
I have invited you to the repo I am using.  Is that suitable for you?  I cannot guarantee it will build and run for you though, sorry.

**Comment by GervinFung** [comment]
> Hi, thank you for the reply. In principle. yes, I understand. However, I do receive the following error in the above case:
> 
> ```
> Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/mnt/Data/Repos/Demo-Project/node_modules/date-fns/add' is not supported resolving ES modules imported from /mnt/Data/Repos/Demo-Project/build/Model/UserSession.js
> Did you mean to import date-fns/add/index.js?
>     at new NodeError (node:internal/errors:387:5)
>     at finalizeResolution (node:internal/modules/esm/resolve:400:17)
>     at moduleResolve (node:internal/modules/esm/resolve:965:10)
>     at defaultResolve (node:internal/modules/esm/resolve:1173:11)
>     at nextResolve (node:internal/modules/esm/loader:173:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
>     at link (node:internal/modules/esm/module_job:75:36) {
>   code: 'ERR_UNSUPPORTED_DIR_IMPORT',
>   url: 'file:///mnt/Data/Repos/Demo-Project/node_modules/date-fns/add'
> }
> ```
> 
> So this made me think that perhaps there was a case not covered. date-fns/add/index.js does exist, and the bare import specifier of a default export seems a valid syntax for ESM, so wasn't sure why Node threw the error.
> 
> The transpiled UserSession.js file also contains `import add from 'date-fns/add';`.
> 
> Using `import { add } from 'date-fns';` works and is always output unaltered. Apologies if this issue is unrelated to your package.

Did u meant that
`import { add } from 'date-fns` works
`import add from 'date-fns/add` doesn't

**Comment by GervinFung** [comment]
Is their package problem, which means

This `import { add } from 'date-fns works` works well
But this `import add from 'date-fns/add` doesn't, have to add `/index.js` at the end of import

Should be fixed in version 3 like they said

Do look at the links below, some others faced ur issue too

[Discussion 1](https://github.com/date-fns/date-fns/discussions/1819)
[Issue 1](https://github.com/date-fns/date-fns/issues/2629)

I was quite shocked when u first point out to me this problem, bcoz I'm sure it's their package problem, as `ts-add-js-extension` doesn't deal with packages, just ur relative import/export statements. Nonethless, I've requested to look at ur repo/example to check the overall usage of the `date-fns` and `ts-add-js-extension` to make sure there is nothing weird. So yeah, it is their package problem

Hope it helps

**Comment by staplespeter** [comment]
Thank you, I hope it was not too much of a distraction for you, and sorry to have taken your time with it.

**Comment by GervinFung** [comment]
> Thank you, I hope it was not too much of a distraction for you, and sorry to have taken your time with it.

Don't be sorry at all, we all need help after all
