### ISSUE TITLE
Feature request: add .js extendsion for .d.ts only dir

### ISSUE THREAD

**Issue by xiaoxiangmoe** [GervinFung/ts-add-js-extension#41]
If our directory has only .d.ts file. We should also add .js for import

**Comment by xiaoxiangmoe** [comment]
For example:

* using tsc with --decalarationOnly generate dir `types/esm/` with only `.d.ts` file.
* using rollup or esbuild or something else to generate file `dist/index.mjs`.

ts-add-js-extension will not working. We need fix it.

**Comment by GervinFung** [comment]
> For example:
> 
> * using tsc with --decalarationOnly generate dir `types/esm/` with only `.d.ts` file.
> * using rollup or esbuild or something else to generate file `dist/index.mjs`.
> 
> `ts-add-js-extension --dir=types/esm` will not working. We need fix it.

I'll check it tonight
The last thing u mentioned, I'll fix it too, I think I should be able to fix it by Friday night, don't worry

**Comment by GervinFung** [comment]
> For example:
> 
> * using tsc with --decalarationOnly generate dir `types/esm/` with only `.d.ts` file.
> * using rollup or esbuild or something else to generate file `dist/index.mjs`.
> 
> `ts-add-js-extension --dir=types/esm` will not working. We need fix it.

I've check that `ts-add-js-extension --dir=types/esm` works in both Windows and Linux, is it not working under certain circumstances
I am still thinking about other problem u pointed out

**Comment by GervinFung** [comment]
> > For example:
> > 
> > * using tsc with --decalarationOnly generate dir `types/esm/` with only `.d.ts` file.
> > * using rollup or esbuild or something else to generate file `dist/index.mjs`.
> > 
> > `ts-add-js-extension --dir=types/esm` will not working. We need fix it.
> 
> I've check that `ts-add-js-extension --dir=types/esm` works in both Windows and Linux, is it not working under certain circumstances I am still thinking about other problem u pointed out

I think I am having a misunderstanding here, u mean `types/esm` wont work for the problem u pointed out right, not for general use case, right?

**Comment by xiaoxiangmoe** [comment]
It's for the use case that if we have a dir only contain .d.ts files, without any .js file.

**Comment by xiaoxiangmoe** [comment]
@GervinFung See this commit https://github.com/xiaoxiangmoe/ts-add-js-extension/commit/efcf31441a950790bfb1e61114d469482434fd7c

**Comment by GervinFung** [comment]
Now I am still unsure what method to use

**Comment by GervinFung** [comment]
@xiaoxiangmoe, is there a use case to add `.mjs` extension too? If there is no need, I think it would be ez to solve this issue

**Comment by xiaoxiangmoe** [comment]
@GervinFung Hi, I think there is no need for add `.mjs` extension, because there is no coresponse tsconfig settings.

**Comment by GervinFung** [comment]
@xiaoxiangmoe Sorry for the late reply, I want to know/double confirm that this feature only involves es module, and not commonjs

**Comment by GervinFung** [comment]
@xiaoxiangmoe I pushed the changes, it should be able to solve this issue, can u try it out and let me know?

**Comment by GervinFung** [comment]
@xiaoxiangmoe let me know how it goes

**Comment by xiaoxiangmoe** [comment]
Hi, your test case seems wrong.

Try to change `"skipLibCheck": true` to `"skipLibCheck": false` and see your dir `test/process/source/dts`

**Comment by GervinFung** [comment]
@xiaoxiangmoe I fixed the type-checking error, the most important part is the output right

**Comment by GervinFung** [comment]
@xiaoxiangmoe hello, what do u think? Or my thought is wrong

**Comment by xiaoxiangmoe** [comment]
I change your `tsconfig.json` from `"skipLibCheck": true` to `"skipLibCheck": false`

Then I see

<img width="342" alt="image" src="https://github.com/GervinFung/ts-add-js-extension/assets/8111351/bbb425f9-5c5e-4129-ab64-8b37c19d8261">
<img width="385" alt="image" src="https://github.com/GervinFung/ts-add-js-extension/assets/8111351/7222d150-f646-4ee7-8b2a-e99a3c54148b">

**Comment by xiaoxiangmoe** [comment]
The only way to make it works well is 
<img width="363" alt="image" src="https://github.com/GervinFung/ts-add-js-extension/assets/8111351/f14a89bd-3d2a-460a-a18d-e7f6edf83fbf">

So I think there is no need for add .mjs extension.

**Comment by xiaoxiangmoe** [comment]
> Can we have 100% confidence `ts-add-js-extension` will work when I remove the `.mjs` case?

Yes. we needn't handle .mjs case. The only thing we need handle is .js case.

**Comment by GervinFung** [comment]
In that case, this tool cane simplified a lot, I think I can remove the functionality of checking whether the imported/exported file exists or not, since we can safely assume the case to handle is always `.js`. We only need to check whether it's `dts or `js` only, then append the file extension. Is there anything that I miss?

**Comment by GervinFung** [comment]
@xiaoxiangmoe

**Comment by xiaoxiangmoe** [comment]
nothing miss😳
that's same as what I think.

**Comment by GervinFung** [comment]
@xiaoxiangmoe 你好，很抱歉这个问题花了这么长时间才解决，因为

1. 我是6月15日才找到工作的，距我辞职已经5个月了, 那时是我第一次有时间回复你
2. 我有一份很接近“第二份工作”的定义工作，我忙着做他们的事情

再次，很抱歉花了我这么长时间才解决，感谢你的耐心，如果一切正常，我将合并新分支并发布它

**Comment by xiaoxiangmoe** [comment]
There is nothing wrong with your implementation.
But the test case doesn't seem to pass tsc. I modified your test case to make it conform to our actual usage.

see here https://github.com/xiaoxiangmoe/ts-add-js-extension/commit/40c0e01b908a40131cde918ae3a3c699c4376fbd

**Comment by GervinFung** [comment]
@xiaoxiangmoe I updated, is there anything I can help with?

**Comment by GervinFung** [comment]
@xiaoxiangmoe I published `1.6.0`
