### ISSUE TITLE
Hello,your package give us very good service，But there's a little regret .It is not surport window

### ISSUE THREAD

**Issue by JhonLandy** [GervinFung/ts-add-js-extension#50]
https://github.com/GervinFung/ts-add-js-extension/blob/2fe9f3f81e56e68694601524499e1bd26844c9d0/src/traverse-and-update.ts#L14C6-L14C6

**Comment by GervinFung** [comment]
Hi, I tried to use in on Windows and setup CICD for Windows. It's working on the latest version of this package as @xiaoxiangmoe pointed out this bug and fixed it too
Are u using the latest version of this package? Or there is a bug in the latest version too?

**Comment by JhonLandy** [comment]
sorry, Thank you for reminding me!

**Comment by JhonLandy** [comment]
sorry, Thank you for reminding me!
