### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by solxiom** [GervinFung/ts-add-js-extension#59]
After upgrading to `1.5.7`, I get an error:

```shell
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/<user>/Projects/<X>/node_modules/ts-add-js-extension/build/mjs/read-write' imported from /home/<user>/Projects/<X>/node_modules/ts-add-js-extension/build/mjs/index.js
```

Any workarounds for this?

**Comment by GervinFung** [comment]
@solxiom I found the issue that caused this issue, it's fixed, thanks for your feedback too, making the feedback loop is quick

**Comment by solxiom** [comment]
@GervinFung, I just pulled down your latest commit and can confirm that the bug has been fixed. The issue is now resolved on my end, and everything is working as expected. I appreciate your prompt response and action to correct the problem. I will close this issue now. Keep up the great work!
