### ISSUE TITLE
One import is not changed, even though others are

### ISSUE THREAD

**Issue by jvanbruegge** [GervinFung/ts-add-js-extension#82]
Hi, we recently added this for [snabbdom](https://github.com/snabbdom/snabbdom), but there seems to be a bug.
In all the files in the build folder the extension is properly added except for `jsx.js`, the top of the file looks like this:
```js
import { vnode } from "./vnode.js";
import { h } from "./h";
export function Fragment(data, ...children) {
```
This means the file is getting processed, but for some reason the last import is not. All other files are fine.

I will work around this for now using search and replace.

**Comment by GervinFung** [comment]
hey @jvanbruegge, thank you for raising this issue to me, I just saw this in my email. I'll take a look and get back to you

**Comment by GervinFung** [comment]
@jvanbruegge the bug should be fixed now, would you like to give it a try before I publish it?

**Comment by GervinFung** [comment]
@jvanbruegge is everything working well on your side?

**Comment by jvanbruegge** [comment]
Yes, 1.6.1 is working as expected, all imports are changed
